---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /integrity-source-garethjevans-org-monorepository
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: integrity.monorepository.source.garethjevans.org
  rules:
  - apiGroups:
    - source.garethjevans.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - monorepositories
  sideEffects: None
