---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monorepo-role
  namespace: dev
rules:
  - apiGroups:
      - source.garethjevans.org
    resources:
      - monorepositories
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - source.garethjevans.org
    resources:
      - monorepositories/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monorepo-rolebinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monorepo-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dev