---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: config-overlay
  namespace: default
spec:
  interval: 5m
  url: https://github.com/garethjevans/filter-controller
  ref:
    branch: main
---
apiVersion: source.garethjevans.org/v1alpha1
kind: Filter
metadata:
  name: foo-app-source
  namespace: default
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    name: config-overlay
