apiVersion: source.garethjevans.org/v1alpha1
kind: MonoRepository
metadata:
  name: where-for-dinner-api-gateway
  namespace: default
spec:
  source:
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: where-for-dinner
      namespace: default
    spec:
      interval: 5m
      url: https://github.com/garethjevans/where-for-dinner
      ref:
        branch: main
  include: |
    /pom.xml
    /where-for-dinner-api-gateway
    !.*
    !**/src/test/**