#@ load("@ytt:data", "data")
---
apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  name: monorepository.apps.tanzu.vmware.com
spec:
  release:
    - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
            - kapp: {}
          template:
            - ytt:
                paths:
                  - carvel/config.yaml
            - kbld:
                paths:
                  - kbld-config.yaml
                  - carvel/config.yaml
      export:
        - imgpkgBundle:
            image: #@ data.values.build.registry_host + "/" + data.values.build.registry_project + "/monorepository-bundle"
            useKbldImagesLock: true
          includePaths:
            - carvel/config.yaml
